# Analysing ACL dataset

* Proximity of train and test
* Relation distribution

In [2]:
# This contains codes and data downloaded from http://ttic.uchicago.edu/~kgimpel/commonsense.html
ACL_ROOT_PATH = "/u/jastrzes/l2lwe/ACL_CKBC/"

In [5]:
import pandas as pd
import os
import matplotlib.pylab as plt
%matplotlib inline

In [7]:
train100 = pd.read_csv(os.path.join(ACL_ROOT_PATH, "commonsendata/Training/new_omcs100.txt"), sep="\t")
test = pd.read_csv(os.path.join(ACL_ROOT_PATH, "commonsendata/Eval/conceptnet/new_omcs_test.txt"), sep="\t")
train100.columns = ['rel', 'head', 'tail', 'score']
test.columns = ['rel', 'head', 'tail', 'score']

## Proximity train & test

In [8]:
train100.query("rel=='UsedFor' and head=='tooth'") # Tuple from test

           rel   head         tail     score
4584   UsedFor  tooth         bite  3.000000
11358  UsedFor  tooth        grind  2.584963
19938  UsedFor  tooth   grind food  2.321928
29752  UsedFor  tooth         chew  2.321928
30260  UsedFor  tooth          eat  2.321928
34308  UsedFor  tooth      griding  2.000000
34324  UsedFor  tooth        crush  2.000000
34383  UsedFor  tooth          rip  2.000000
78466  UsedFor  tooth     eat with  1.584963
93508  UsedFor  tooth  cut and rip  1.584963

In [9]:
train100.query("rel=='AtLocation' and head=='rosebush'") # Tuple from test

              rel      head                     tail     score
1199   AtLocation  rosebush            flower garden  3.321928
1797   AtLocation  rosebush                back yard  3.169925
3295   AtLocation  rosebush                landscape  3.000000
4393   AtLocation  rosebush                     park  3.000000
4501   AtLocation  rosebush               flower bed  3.000000
8136   AtLocation  rosebush                   garden  2.807355
8525   AtLocation  rosebush                    earth  2.584963
9108   AtLocation  rosebush               front yard  2.584963
9541   AtLocation  rosebush           botanic garden  2.584963
9800   AtLocation  rosebush         botanical garden  2.584963
10439  AtLocation  rosebush           garden catalog  2.584963
11576  AtLocation  rosebush                 outdoors  2.584963
13859  AtLocation  rosebush            gramma garden  2.584963
16061  AtLocation  rosebush  white house rose garden  2.321928
18921  AtLocation  rosebush                    store  2.321928
29116  AtLocation  rosebush           flower nursery  2.321928
31016  AtLocation  rosebush                     yard  2.321928
35063  AtLocation  rosebush            formal garden  2.000000
42864  AtLocation  rosebush                      pot  2.000000
42866  AtLocation  rosebush                    bloom  2.000000
45674  AtLocation  rosebush            garden center  2.000000
81880  AtLocation  rosebush                    house  1.584963
85845  AtLocation  rosebush                rose show  1.584963
86966  AtLocation  rosebush          bloom in spring  1.584963
87475  AtLocation  rosebush                     rose  1.584963

## Relation distribution

Different from whole ConceptNet5

In [10]:
test.groupby("rel").count()

                  head  tail  score
rel
AtLocation         479   479    479
CapableOf          280   280    280
Causes              93    93     93
CausesDesire         6     6      6
CreatedBy            5     5      5
DefinedAs            2     2      2
Desires             17    17     17
HasA                98    98     98
HasFirstSubevent     1     1      1
HasPrerequisite    226   226    226
HasProperty        143   143    143
HasSubevent        170   170    170
IsA                395   395    395
MadeOf              28    28     28
MotivatedByGoal     15    15     15
NotCapableOf        20    20     20
NotHasProperty       4     4      4
NotIsA               1     1      1
PartOf              52    52     52
ReceivesAction      22    22     22
RelatedTo            3     3      3
UsedFor            339   339    339